name = "highDimMM"
uuid = "508b3551-8cd2-4bd7-b10f-e4bf0d8fd377"
authors = ["Zhuoyan Xu <zxu68341@icloud.com> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
